# Generated by Django 4.1.5 on 2023-01-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinterest_userprofile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='accounts.userinterest'),
        ),
    ]
